---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-node-tek
spec:
  serviceAccountName: tekton-triggers-example-sa-tek
  triggers:
    - name: normal-push
      interceptors:
        - github:
            secretRef:
              secretName: githubsecret-tek
              secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - name: git-repo-name-tek
        - name: git-common-tek
        - name: number-12
      template:
        name: node-pipe
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-node-13-tek
spec:
  serviceAccountName: tekton-triggers-example-sa-tek
  triggers:
    - name: normal-push
      interceptors:
        - github:
            secretRef:
              secretName: githubsecret-tek
              secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - name: git-repo-name-tek
        - name: git-common-tek
        - name: number-13
      template:
        name: node-pipe

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor-tek
spec:
  serviceAccountName: tekton-triggers-example-sa-tek
  triggers:
    - name: normal-push
      interceptors:
        - github:
            secretRef:
              secretName: githubsecret-tek
              secretKey: secretToken
            eventTypes:
              - push
        - cel:
            filter: "!body.ref.contains('master')"
        - cel:
            filter: "!body.ref.contains('develop')"
      bindings:
        - name: git-repo-full-name-tek
        - name: git-repo-sha-tek
        - name: git-repo-target-url-tek
      template:
        name: git-status-pipe
    - name: master-push
      interceptors:
        - github:
            secretRef:
              secretName: githubsecret-tek
              secretKey: secretToken
            eventTypes:
              - push
        - cel:
            filter: "body.ref.contains('master')"
      bindings:
        - name: git-repo-name-tek
        - name: git-common-tek
      template:
        name: pipeline-master-tek
    - name: dev-push
      interceptors:
        - github:
            secretRef:
              secretName: githubsecret-tek
              secretKey: secretToken
            eventTypes:
              - push
        - cel:
            filter: "body.ref.contains('develop')"
      bindings:
        - name: git-common-tek
        - name: git-repo-name-tek
      template:
        name: pipeline-dev-tek
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: tek-demo-connect
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: tekton-tek
spec:
  rules:
    - host: tek-demo.live
      http:
        paths:
          - backend:
              serviceName: el-github-listener-interceptor-tek
              servicePort: http-listener
            path: /docker
          - backend:
              serviceName: el-github-listener-node-tek
              servicePort: http-listener
            path: /node
          - backend:
              serviceName: el-github-listener-node-13-tek
              servicePort: http-listener
            path: /node13
  tls:
    - hosts:
        - tek-demo.live
      secretName: tek-web-tls-secret-tek
