apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-pipe
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: number
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: node-
      spec:
        pipelineRef:
          name: node-pipe
        params:
          - name: node-version
            value: $(params.number)
          - name: slack-secret
            value: webhook-secret-tek
          - name: slack-message-url
            value: $(params.gitrepositoryurl)
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.gitrevision)
                - name: url
                  value: $(params.gitrepositoryurl)
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              metadata:
                generateName: shared-data-
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 0.2Gi
        serviceAccountName: build-bot-tek
