apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-common-tek
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-ref-tek
spec:
  params:
    - name: gitref
      value: $(body.ref)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-repo-name-tek
spec:
  params:
    - name: gitreponame
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-repo-full-name-tek
spec:
  params:
    - name: gitfullname
      value: $(body.repository.full_name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-repo-target-url-tek
spec:
  params:
    - name: giturl
      value: $(body.head_commit.url)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-repo-sha-tek
spec:
  params:
    - name: gitsha
      value: $(body.head_commit.id)
