apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: single-image-pipe-tek
spec:
  resources:
    - name: source-repo
      type: git
    - name: argocd-repo
      type: git
    - name: image
      type: image
  params:
    - name: slack-secret
      type: string
    - name: slack-message-url
      type: string
  tasks:
    - name: send-slack-start
      params:
        - name: webhook-secret
          value: $(params.slack-secret)
        - name: message
          value: The Pipeline for $(params.slack-message-url) started
      taskRef:
        name: send-to-channel-slack
    - name: build
      taskRef:
        name: build-push-tek
      params:
        - name: pathToDockerFile
          value: /workspace/workspace/Dockerfile
        - name: pathToContext
          value: /workspace/workspace/
      resources:
        inputs:
          - name: workspace
            resource: source-repo
        outputs:
          - name: builtImage
            resource: image
      runAfter:
        - send-slack-start
    - name: push-dev
      conditions:
        - conditionRef: is-branch
          params:
            - name: branchref
              value: "develop"
          resources:
            - name: workspace
              resource: argocd-repo
      taskRef:
        kind: Task
        name: git-dev-tek
      runAfter:
        - build
      resources:
        inputs:
          - name: workspace
            resource: argocd-repo
    - name: push-master
      conditions:
        - conditionRef: is-branch
          params:
            - name: branchref
              value: "master"
          resources:
            - name: workspace
              resource: argocd-repo
      taskRef:
        kind: Task
        name: git-master-tek
      runAfter:
        - build
      resources:
        inputs:
          - name: workspace
            resource: argocd-repo
    - name: send-slack-end
      conditions:
      params:
        - name: webhook-secret
          value: $(params.slack-secret)
        - name: message
          value: "The Pipeline for $(params.slack-message-url) finished"
      taskRef:
        name: send-to-channel-slack
      runAfter:
        - build
        - push-master
